name: Check Timespent in Linked Issues

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  check-timespent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (just in case)
        uses: actions/checkout@v4

      - name: Get linked issues
        id: get-issues
        run: |
          # Check if pull_request_number is passed via workflow_dispatch
          PR_NUMBER="${{ github.event.pull_request.number }}"

          # If PR_NUMBER is empty, we fallback to repository context
          if [ -z "$PR_NUMBER" ]; then
            echo "No PR number found, using repository context only."
            PR_BODY=$(gh pr view --repo ${{ github.repository }} --json body -q .body)
          else
            echo "Using PR number: $PR_NUMBER"
            PR_BODY=$(gh pr view "$PR_NUMBER" --repo ${{ github.repository }} --json body -q .body)
          fi

          echo "PR Body: $PR_BODY"
          ISSUE_NUMBERS=$(echo "$PR_BODY" | grep -oE '#[0-9]+' | tr -d '#' | tr '\n' ' ')
          echo "Found Issues: $ISSUE_NUMBERS"
          echo "ISSUE_NUMBERS=$ISSUE_NUMBERS" >> $GITHUB_ENV
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Timespent in Issues
        id: check-timespent
        run: |
          MISSING_TIMESPENT=""
          for ISSUE in $ISSUE_NUMBERS; do
            BODY=$(gh issue view "$ISSUE" --json body -q .body)
            if echo "$BODY" | grep -q '/Timespent Xh Ym'; then
              MISSING_TIMESPENT+="#$ISSUE "
            fi
          done

          if [ -n "$MISSING_TIMESPENT" ]; then
            COMMENT_BODY="❌ The following issues are missing an updated Timespent value: $MISSING_TIMESPENT
            Please update them before merging this PR."
            echo "$COMMENT_BODY"

            # Request changes on the PR (this blocks the merge)
            gh pr review $PR_NUMBER --repo ${{ github.repository }} --request-changes --body "$COMMENT_BODY"
            
          else
            # If Timespent is present, leave an approval (optional)
            echo "Timespent updated! PR is approved."
            gh pr review $PR_NUMBER --repo ${{ github.repository }} --approve
            
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
