name: Check Timespent in Linked Issues

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  issue_comment:
    types: [created]

jobs:
  check-timespent:
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment' && contains(github.event.comment.body, 'Updated Timespent') || ${{ github.event.issue.pull_request }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get linked issues
        id: get-issues
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"

          # Fetch PR body
          PR_BODY=$(gh pr view "$PR_NUMBER" --repo ${{ github.repository }} --json body -q .body)
          
          echo "PR Body: $PR_BODY"
          ISSUE_NUMBERS=$(echo "$PR_BODY" | grep -oE '#[0-9]+' | tr -d '#' | tr '\n' ' ')
          echo "Found Issues: $ISSUE_NUMBERS"
          
          # Export issue numbers and PR number to environment variables
          echo "ISSUE_NUMBERS=$ISSUE_NUMBERS" >> $GITHUB_ENV
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Timespent in Issues
        id: check-timespent
        run: |
          MISSING_TIMESPENT=""
          for ISSUE in $ISSUE_NUMBERS; do
            BODY=$(gh issue view "$ISSUE" --json body -q .body)
            if ! echo "$BODY" | grep -qE '/Timespent [0-9]h [1-6]?[0-9]m'; then
              MISSING_TIMESPENT+="#$ISSUE "
            fi
          done

          if [ -n "$MISSING_TIMESPENT" ]; then
            COMMENT_BODY="❌ The following issues are missing an updated Timespent value: $MISSING_TIMESPENT
            Please comment 'Updated Timespent' on this PR when you have updated them."
            echo "$COMMENT_BODY"
            
            # Post comment on the PR
            gh pr comment $PR_NUMBER --repo ${{ github.repository }} --body "$COMMENT_BODY"
            
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
