name: Rerun PR Check When Issue is Updated

on:
  issues:
    types: [edited]

jobs:
  trigger-pr-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Find Related PRs
        id: find-prs
        run: |
          PRS=$(gh pr list --state open --repo ${{ github.repository }} --json number,body -q '.[] | select(.body | test("#${{ github.event.issue.number }}")) | .number')
          echo "Related PRs: $PRS"
          echo "RELATED_PRS=$PRS" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Re-run PR Workflow
        if: env.RELATED_PRS != ''
        run: |
          # Split RELATED_PRS into an array
          IFS=$'\n' read -r -d '' -a PR_ARRAY <<< "${{ env.RELATED_PRS }}"
          
          # Loop over PR numbers
          for PR in "${PR_ARRAY[@]}"; do
            # Run the workflow for each PR
            gh workflow run verify-timespent.yml --repo ${{ github.repository }} -f pull_request_number="$PR"
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
