name: Check Timespent in Linked Issues

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  check-timespent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (just in case)
        uses: actions/checkout@v4

      - name: Authenticate GitHub CLI
        run: gh auth status
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get linked issues
        id: get-issues
        run: |
          if [[ "${{ github.event_name }}" == "issues" ]]; then
            echo "Triggered by issue update, finding related PRs..."
            PRS=$(gh pr list --state open --repo ${{ github.repository }} --json number,body -q '.[] | select(.body | test("#${{ github.event.issue.number }}")) | .number')
            echo "Related PRs: $PRS"
            echo "RELATED_PRS=$PRS" >> $GITHUB_ENV
          else
            PR_BODY=$(gh pr view ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --json body -q .body)
            ISSUE_NUMBERS=$(echo "$PR_BODY" | grep -oE '#[0-9]+' | tr -d '#')
            echo "ISSUE_NUMBERS=$ISSUE_NUMBERS" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Timespent in Issues
        id: check-timespent
        run: |
          MISSING_TIMESPENT=""
          for ISSUE in $ISSUE_NUMBERS; do
            BODY=$(gh issue view "$ISSUE" --repo ${{ github.repository }} --json body -q .body)
            if echo "$BODY" | grep -q '/Timespent Xh Ym'; then
              MISSING_TIMESPENT+="#$ISSUE "
            fi
          done

          if [ -n "$MISSING_TIMESPENT" ]; then
            COMMENT_BODY="❌ The following issues are missing an updated Timespent value: $MISSING_TIMESPENT
            Please update them before merging this PR."
            echo "$COMMENT_BODY"

            # Post comment on the PR(s) that reference the issue
            if [[ -n "$RELATED_PRS" ]]; then
              for PR in $RELATED_PRS; do
                gh pr comment "$PR" --repo ${{ github.repository }} --body "$COMMENT_BODY"
              done
            else
              gh pr comment ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --body "$COMMENT_BODY"
            fi

            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


